version: '3.8'

services:
  solid-pds:
    build: .
    container_name: solid-pds
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
      - DATA_ROOT=/app/data
      - OIDC_ISSUER=https://oidc.solid.gov.uk
    volumes:
      - pds-data:/app/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Mock services for development
  mock-oidc:
    build:
      context: .
      dockerfile: Dockerfile.mock-oidc
    container_name: mock-oidc
    ports:
      - "8001:8001"
    environment:
      - NODE_ENV=development
    profiles:
      - development
    restart: unless-stopped

  mock-did-ion:
    build:
      context: .
      dockerfile: Dockerfile.mock-did
    container_name: mock-did-ion
    ports:
      - "8002:8002"
    environment:
      - NODE_ENV=development
    profiles:
      - development
    restart: unless-stopped

volumes:
  pds-data:
    driver: local

networks:
  default:
    name: solid-pds-network
